- name: Install  and configure nginx
  hosts: my-servers
  become: yes

  tasks:
    - name: install nginx
      apt:
       name: nginx
       state: present
       update_cache: yes

    - name: Ensure nginx
      service:
        name: nginx
        state: started
        enabled: yes
